import sys, os
from pathlib import Path
from sqlalchemy.orm import Session
from app.db.database import SessionLocal, engine
from app.models.models import Case, Report
from app.services.reporting.pdf_generator import generate_pdf_report
from datetime import datetime

db = SessionLocal()
# Find the case we used for real data test
c = db.query(Case).order_by(Case.created_at.desc()).first()
if not c:
    print("No case found")
    sys.exit(1)
print(f"Generating PDF for Case: {c.id}")

pdf_path = generate_pdf_report(c, db)

report = Report(
    case_id=c.id,
    file_path=pdf_path,
    generated_at=datetime.utcnow(),
    remarks="Auto-generated by M9 real test"
)
db.add(report)
db.commit()

print(f"PDF PATH: {pdf_path}")
exists = os.path.exists(pdf_path)
size = os.path.getsize(pdf_path) if exists else 0
print(f"Exists: {exists}")
print(f"Size: {size} bytes")

db.close()
