from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session
from datetime import datetime

from app.db.database import get_db
from app.models.models import User, Case, Report, Prediction, AuditLog
from app.api.deps import get_current_user
from app.schemas.schemas import ReportResponse
from app.services.reporting.pdf_generator import generate_pdf_report

from fastapi.responses import FileResponse
from pathlib import Path
import uuid

router = APIRouter(prefix="/api/reports", tags=["reports"])

@router.get("/case/{case_id}", response_model=list[ReportResponse])
def list_reports(case_id: str, db: Session = Depends(get_db), current_user: User = Depends(get_current_user)):
    return db.query(Report).filter(Report.case_id == case_id).order_by(Report.generated_at.desc()).all()

@router.get("/download/{report_id}")
def download_report(report_id: str, db: Session = Depends(get_db), current_user: User = Depends(get_current_user)):
    report = db.query(Report).filter(Report.id == report_id).first()
    if not report:
        raise HTTPException(status_code=404, detail="Report not found")
    if not Path(report.file_path).exists():
        raise HTTPException(status_code=404, detail="PDF file not found on disk")
    return FileResponse(report.file_path, media_type='application/pdf', filename=f"report_{report.id}.pdf")

@router.post("/cases/{case_id}/generate", response_model=ReportResponse)
def generate_report(case_id: str, db: Session = Depends(get_db), current_user: User = Depends(get_current_user)):
    """
    Generate a PDF report for an analyzed case.
    """
    case = db.query(Case).filter(Case.id == case_id).first()
    if not case:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Case not found")
        
    # Optional: check if the user has access. Assuming all authenticated users can for now,
    # or if we need to restrict:
    # if case.created_by != current_user.id and not current_user.is_admin:
    #     raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Not authorized")
        
    # Check if analysis exists
    predictions = db.query(Prediction).filter(Prediction.case_id == case.id).count()
    if predictions == 0:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="No analysis results available for this case")
        
    report_id = str(uuid.uuid4())
    try:
        pdf_path = generate_pdf_report(case, db, report_id=report_id)
    except Exception as e:
        raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail=f"PDF generation failed: {str(e)}")
        
    # Save Report to DB
    report = Report(
        id=report_id,
        case_id=case.id,
        file_path=pdf_path,
        generated_at=datetime.utcnow(),
        remarks="Auto-generated by M9"
    )
    db.add(report)
    db.commit()
    db.refresh(report)
    
    # Audit log
    db.add(AuditLog(user_id=current_user.id, action="generate_report", target_id=report.id))
    db.commit()
    
    return report
